MOUSEKEY_ENABLE = yes    # Mouse keys
# RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes

AUTO_SHIFT_ENABLE = yes
NO_AUTO_SHIFT_SPECIAL = no
# UNICODE_ENABLE = yes
UNICODEMAP_ENABLE = yes

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes





SEND_STRING_ENABLE = yes
